"""
Data loading and processing utilities for the Pigeon project.
Python translations of the MATLAB getPigeon_* functions.

Main pipeline
-------------
1. ``get_data_table``        — reads per-subject CSV files, calls
   ``get_bounds`` on the resulting step sequences, optionally merges the
   six task blocks into three, and applies ``apply_bias_corrections``.
2. ``get_bounds``            — from raw step sequences infers the bound
   (decision threshold position at the time of choice), DT (steps after
   NDT), RT (total steps), and the congruence array (fraction of trials
   where the pigeon's position at each NDT lag aligns with the final choice).
3. ``get_good_trial_array``  — returns a boolean mask implementing the
   standard quality filter: DT ≥ 2, trial_number ≥ 10, wall_hit = False.
4. ``apply_bias_corrections`` — applies per-(DT, SNR-bin) linear correction
   to the inferred bound using coefficients from a .mat file generated by
   ``notebooks/Make_biasCorrection.ipynb``.

Key constants
-------------
RAW_DATA_DIR : Path
    Default path to the top-level raw CSV data directory (from pathDefaults).
WALL : float
    Screen-edge limit (0.75).  Trials where any step position reaches this
    limit are flagged ``wall_hit = True`` and excluded by
    ``get_good_trial_array``.
"""

import os
import glob
import numpy as np
import pandas as pd
import scipy.io


from .pathDefaults import RAW_DATA_DIR, BIAS_CORRECTION_FILE

WALL = 0.75  # screen-edge limit; trials where any step position reaches |WALL| are flagged wall_hit = True


def get_data_table(task_type="MX", data_dir=RAW_DATA_DIR, blocks="all",
                   combine_snr=True, correct_bias=BIAS_CORRECTION_FILE):
    """
    Load and return a DataFrame of trial data.
    Translated from getPigeon_dataTable.m

    Parameters
    ----------
    task_type : str
        'OL' (blocked SNR), 'MX' (mixed SNR), or 'PD' (predefined bound).
        The 'CP' (change-point) task is not yet implemented in Python;
        use the MATLAB pipeline to generate pre-computed summaries.
    data_dir : str
        Path to the data directory
    blocks : str or list
        'all' or list of block numbers to include
    combine_snr : bool
        If True, combine 6 blocks into 3 (blocked/mixed SNR logic)
    correct_bias : str or None
        Path to .mat bias correction file, or None to skip

    Returns
    -------
    pd.DataFrame with columns:
        subject_index, block_index, trial_number, bound, abs_bound,
        RT, DT, change_point, choice, correct, coin_count, snr,
        steps, congruence
    """
    csv_pattern = os.path.join(data_dir, f"Pigeon_{task_type}", "prolificcsvs", "*.csv")
    files = sorted(glob.glob(csv_pattern))

    all_tables = []

    for subject_index, fpath in enumerate(files, start=1):
        print(f"{subject_index:3d}: {fpath}")

        tmp = pd.read_csv(fpath, encoding="utf-8-sig")

        # Keep only rows with a valid trial_number
        good = tmp["trial_number"].notna()
        if isinstance(blocks, list):
            good = good & tmp["block_number"].isin(blocks)
        tmp = tmp[good].reset_index(drop=True)

        if task_type in ("OL", "MX"):
            cols = ["block_number", "trial_number", "pigeon_steps", "choice",
                    "correct", "steps_count", "step_mean_val", "step_std_val", "coins_count"]
            tmp = tmp[cols].copy()
        else:  # PD
            # PD uses paired rows: trial row + next row for pigeon data
            indices = tmp.index.tolist()
            trial_rows = tmp.loc[indices]
            next_rows = tmp.loc[[i + 1 for i in indices]].reset_index(drop=True)
            tmp = pd.concat([
                trial_rows[["block_number", "trial_number", "predefined_bound", "correct"]].reset_index(drop=True),
                next_rows[["pigeon_steps", "choice", "coins_count"]]
            ], axis=1)

        n_trials = len(tmp)
        rows = {
            "subject_index": np.full(n_trials, subject_index),
            "block_index": tmp["block_number"].to_numpy(dtype=float),
            "trial_number": tmp["trial_number"].to_numpy(dtype=float),
            "bound": np.full(n_trials, np.nan),
            "abs_bound": np.full(n_trials, np.nan),
            "RT": np.full(n_trials, np.nan),
            "DT": np.full(n_trials, np.nan),
            "change_point": np.zeros(n_trials),
            "choice": np.full(n_trials, np.nan),
            "correct": np.full(n_trials, np.nan),
            "coin_count": tmp["coins_count"].to_numpy(dtype=float),
            "snr": np.full(n_trials, np.nan),
            "steps": [None] * n_trials,
            "congruence": [None] * n_trials,
            "rt_cutoff": np.ones(n_trials),
        }

        if task_type in ("OL", "MX"):
            rows["snr"] = (tmp["step_mean_val"] / tmp["step_std_val"]).to_numpy(dtype=float)

        # Parse steps and choices per trial
        for tt in range(n_trials):
            steps_str = tmp["pigeon_steps"].iloc[tt]
            if isinstance(steps_str, str):
                steps = np.array([float(x) for x in steps_str.strip('[]').split(',') if x.strip()], dtype=float)
            else:
                steps = np.array([], dtype=float)
            rows["steps"][tt] = steps

            choice_val = tmp["choice"].iloc[tt]
            if isinstance(choice_val, str) and choice_val in ("right", "left"):
                rows["choice"][tt] = 1.0 if choice_val == "right" else 0.0
                correct_val = tmp["correct"].iloc[tt]
                if isinstance(correct_val, str):
                    rows["correct"][tt] = 1.0 if choice_val == correct_val else 0.0
            elif isinstance(choice_val, (int, float)) and np.isfinite(choice_val):
                rows["choice"][tt] = float(choice_val)
                rows["correct"][tt] = float(tmp["correct"].iloc[tt])

            if task_type == "PD":
                rows["bound"][tt] = float(tmp["predefined_bound"].iloc[tt])
                rows["RT"][tt] = len(steps)

        # Compute bounds, DT, RT, congruences for online tasks
        if task_type in ("OL", "MX"):
            bounds, dts, rts, congruence, rt_cutoffs = get_bounds(
                rows["steps"], rows["choice"],
                snr=np.abs(rows["snr"]),
                block_ids=rows["block_index"],
                ndt=None,
            )
            rows["bound"]      = bounds
            rows["DT"]         = dts
            rows["RT"]         = rts
            rows["congruence"] = [congruence] * n_trials
            rows["rt_cutoff"]  = rt_cutoffs

        rows["abs_bound"] = np.abs(rows["bound"])

        all_tables.append(pd.DataFrame(rows))

    data_table = pd.concat(all_tables, ignore_index=True)

    # Flag trials below the per-(subject, block, SNR) RT reliability cutoff.
    data_table["rt_below_cutoff"] = data_table["RT"] < data_table["rt_cutoff"]

    # Mark trials where the pigeon reached the screen edge (|step| >= WALL).
    # On these trials the step logger kept recording after the wall was hit,
    # inflating RT and DT. The wall-hit step itself is the true end of the trial.
    data_table["wall_hit"] = data_table["steps"].apply(
        lambda s: s is not None and len(s) > 0
        and bool(np.any(np.abs(s[np.isfinite(s)]) >= WALL - 1e-9))
    )

    # Combine 6 blocks into 3 if requested
    if combine_snr and sorted(data_table["block_index"].dropna().unique().astype(int)) == list(range(1, 7)):
        block1_snrs = data_table.loc[data_table["block_index"] == 1, "snr"].dropna()
        if len(block1_snrs.abs().unique()) == 1:
            # blocked: remap blocks 4-6 -> 1-3
            for b in range(1, 4):
                data_table.loc[data_table["block_index"] == b + 3, "block_index"] = b
        else:
            # mixed: drop blocks 4-6
            data_table = data_table[data_table["block_index"] <= 3].reset_index(drop=True)

    # Apply bias corrections
    if correct_bias and os.path.exists(correct_bias):
        data_table = apply_bias_corrections(data_table, correct_bias)

    return data_table


def _compute_rt_cutoff(bound_matrix, choices_pm, rts, threshold=0.65, min_trials=5):
    """
    Find the minimum RT cutoff C such that trials with RT >= C have
    max congruence (across NDT lags) >= threshold.

    Iterates from the largest RT down to the smallest. At each candidate
    cutoff r, computes max_k(congruence) for all trials with RT >= r.
    Returns the smallest r for which this still meets the threshold.

    Parameters
    ----------
    bound_matrix : (n_trials, max_ndt) array
    choices_pm   : (n_trials,) array  —  choices coded as ±1
    rts          : (n_trials,) array  —  response times
    threshold    : float              —  congruence threshold (default 0.65)
    min_trials   : int                —  minimum trials per RT bin to compute congruence

    Returns
    -------
    int : minimum RT to include (exclude trials with RT < cutoff).
          Returns 1 if all RTs meet the threshold (no cutoff needed).
    """
    max_ndt  = bound_matrix.shape[1]
    rt_vals  = sorted(np.unique(rts[np.isfinite(rts)].astype(int)))
    cutoff   = 1  # default: no cutoff needed

    for r in reversed(rt_vals):
        mask = np.isfinite(rts) & (rts.astype(int) >= r)
        if mask.sum() < min_trials:
            continue
        max_cong = 0.0
        for k in range(max_ndt):
            lc = mask & (bound_matrix[:, k] != 0)
            if lc.sum() >= min_trials:
                cong = np.mean(np.sign(bound_matrix[lc, k]) == choices_pm[lc])
                max_cong = max(max_cong, cong)
        if max_cong >= threshold:
            cutoff = r   # threshold met; try including one shorter RT
        else:
            break        # adding shorter RT drops below threshold; stop

    return cutoff


def get_bounds(steps_list, choices, max_ndt=5, min_rt=1, snr=None,
               block_ids=None, rt_cutoff_threshold=0.65, ndt=2,
               peak_step_bound=True):
    """
    Compute bounds, decision times, response times, and congruences.
    Translated from getPigeon_bounds.m

    Parameters
    ----------
    steps_list : list of np.ndarray
    choices : array-like of float (0/1)
    max_ndt : int
    min_rt : int
    snr : array-like or None
    block_ids : array-like or None
        Block identifier per trial. If provided, the RT cutoff is computed
        separately for each (block, SNR) combination. If None, a single
        cutoff is computed across all trials.
    rt_cutoff_threshold : float
        Congruence threshold for the RT cutoff (default 0.65). Set to None
        to skip cutoff computation (rt_cutoffs returned as all-ones).
    ndt : int or None
        NDT lag to use for bound extraction. If an integer, all trials use
        this fixed lag (clipped to RT-2). If None, the lag is estimated per
        SNR group as the one that maximises congruence.
    peak_step_bound : bool
        If True (default), apply the peak-step bound correction: for trials
        where the pigeon is moving away from the choice side at the NDT
        crossing, replace the midpoint bound with steps[RT-2-ndt] — the
        earlier, outermost of the two crossing steps (furthest from centre).
        This avoids underestimating the bound when the pigeon has already
        turned around within the crossing window. Set to False to use the
        original midpoint definition.

    Returns
    -------
    bounds : np.ndarray
    dts : np.ndarray
    rts : np.ndarray
    congruences : np.ndarray, shape (max_ndt, n_snrs)
    rt_cutoffs : np.ndarray, shape (n_trials,)
        Per-trial RT cutoff. Trials with RT < rt_cutoffs[i] are below the
        reliability threshold and should be excluded from bound analyses.
    """
    n_trials = len(steps_list)
    choices_pm = np.array(choices) * 2 - 1  # convert 0/1 to -1/+1

    if snr is None:
        snr = np.zeros(n_trials)
    snr = np.asarray(snr)
    unique_snrs = np.unique(snr[np.isfinite(snr)])
    n_snrs = len(unique_snrs)

    if block_ids is None:
        block_ids = np.zeros(n_trials)
    block_ids = np.asarray(block_ids)

    # Build the bound matrix.
    # For each trial, take the last min(RT, max_ndt) step positions, reverse them,
    # and compute midpoints between consecutive pairs.  The midpoint at lag k is:
    #   bound_matrix[i, k] = (steps[RT-1-k] + steps[RT-2-k]) / 2
    # This estimates where the accumulator was when the decision threshold was crossed
    # at NDT lag k steps before the response.
    bound_matrix = np.zeros((n_trials, max_ndt))
    rts = np.full(n_trials, np.nan)

    for ii in range(n_trials):
        these_steps = steps_list[ii]
        these_steps = these_steps[np.isfinite(these_steps)] if these_steps is not None else np.array([])
        rts[ii] = len(these_steps)

        final_steps = these_steps[max(int(rts[ii]) - max_ndt, 0):][::-1]  # reversed
        if len(final_steps) > 1:
            # midpoints between consecutive pairs
            midpoints = final_steps[1:] - np.diff(final_steps) / 2
            bound_matrix[ii, :len(midpoints)] = midpoints

    # Determine the best NDT lag per SNR level using congruence.
    # Congruence at lag k = fraction of trials where sign(bound_matrix[:, k])
    # matches the choice direction (+1 = right, -1 = left).  The lag that
    # maximises congruence is the estimated NDT for that SNR level.
    ndts = np.full(n_trials, np.nan)
    bounds = np.full(n_trials, np.nan)
    congruences = np.full((max_ndt, n_snrs), np.nan)

    for ss, snr_val in enumerate(unique_snrs):
        ls = np.isclose(snr, snr_val)

        for ii in range(max_ndt):
            lc = ls & (bound_matrix[:, ii] != 0)
            if lc.sum() > 5:
                congruences[ii, ss] = np.sum(
                    np.sign(bound_matrix[lc, ii]) == choices_pm[lc]
                ) / lc.sum()

        if ndt is not None:
            # Fixed NDT: use the specified lag for all trials in this SNR group
            ndts[ls] = np.clip(rts[ls] - 2, 0, int(ndt))
        else:
            # Per-SNR NDT: lag with maximum congruence, clipped so NDT <= RT-2
            # (a trial with RT=2 can have NDT at most 0).
            valid_cong = congruences[:, ss]
            if np.any(np.isfinite(valid_cong)):
                max_cong = np.nanmax(valid_cong)
                ci = int(np.where(valid_cong == max_cong)[0][-1])
                # ci=0 -> NDT=0, ci=1 -> NDT=1, etc. (capped by RT-2)
                ndts[ls] = np.clip(rts[ls] - 2, 0, ci)

    # Extract bound for each trial from its NDT lag.
    # With peak_step_bound=True: for trials where the pigeon is moving away from
    # the choice side at the NDT crossing, replace the midpoint with steps[RT-2-k]
    # (the earlier, outermost step — furthest from centre when retreating).
    for bi in np.where(np.isfinite(ndts))[0]:
        k   = int(ndts[bi])
        mid = bound_matrix[bi, k]

        if peak_step_bound and mid != 0:
            sc = steps_list[bi]
            sc = sc[np.isfinite(sc)] if sc is not None else np.array([])
            RT       = int(rts[bi])
            t_later  = RT - 1 - k   # later step (closer to response)
            t_earlier = RT - 2 - k  # earlier step (furthest from centre when retreating)
            if 0 <= t_earlier < len(sc) and t_later < len(sc):
                step_in = sc[t_later] - sc[t_earlier]
                if step_in * np.sign(mid) < 0:  # backward motion at crossing
                    bounds[bi] = sc[t_earlier]
                    continue

        bounds[bi] = mid

    # Remove bounds from very short trials
    bounds[rts < min_rt] = np.nan

    # DT = steps after the NDT period ends (i.e. the "deliberation time")
    dts = np.maximum(0, rts - ndts - 1)

    # Compute RT cutoff per (block, SNR) group.
    # For each group, find the minimum RT such that trials with RT >= that value
    # have max congruence (across NDT lags) >= rt_cutoff_threshold.
    rt_cutoffs = np.ones(n_trials, dtype=float)
    if rt_cutoff_threshold is not None:
        for blk in np.unique(block_ids[np.isfinite(block_ids.astype(float))]):
            for snr_val in unique_snrs:
                group = (np.isclose(block_ids.astype(float), float(blk)) &
                         np.isclose(snr, snr_val))
                if group.sum() < 5:
                    continue
                cutoff = _compute_rt_cutoff(
                    bound_matrix[group],
                    choices_pm[group],
                    rts[group],
                    threshold=rt_cutoff_threshold,
                )
                rt_cutoffs[group] = cutoff

    return bounds, dts, rts, congruences, rt_cutoffs


def get_bounds_from_dv(choices, rts, DV, max_ndt=5, rt_cutoff_threshold=0.65,
                        ndt=2, peak_step_bound=True):
    """
    Like get_bounds but takes a pre-built DV matrix instead of a steps list.

    Intended for vectorised use with simulation output (e.g. bias-correction
    calibration) where DV is already a 2-D numpy array.  The bound logic —
    midpoint construction, NDT selection, peak-step correction, RT cutoff — is
    identical to get_bounds.

    Parameters
    ----------
    choices : (n,) array-like  0 = left, 1 = right
    rts     : (n,) array-like  number of steps taken per trial
    DV      : (n, max_steps) float array  DV[i, t] = pigeon position at step t
    max_ndt : int
    rt_cutoff_threshold : float or None
    ndt     : int or None  fixed NDT lag; None -> pick by max congruence
    peak_step_bound : bool  see get_bounds

    Returns
    -------
    bounds, dts, rts, congruence, rt_cutoffs
        Same semantics as get_bounds; congruence has shape (max_ndt,) with
        no SNR dimension (caller supplies one SNR group at a time).
    """
    n_trials   = len(choices)
    rts        = np.asarray(rts,     dtype=float)
    choices_pm = np.asarray(choices, dtype=float) * 2 - 1

    # ── Build bound matrix (vectorised) ──────────────────────────────────────
    # bound_matrix[i, k] = (DV[i, RT-1-k] + DV[i, RT-2-k]) / 2
    bound_matrix = np.zeros((n_trials, max_ndt))
    for k in range(max_ndt):
        rows = np.where(rts >= k + 2)[0]
        if len(rows):
            r = rts[rows].astype(int)
            bound_matrix[rows, k] = (DV[rows, r - 1 - k] + DV[rows, r - 2 - k]) / 2

    # ── NDT selection ────────────────────────────────────────────────────────
    congruence = np.full(max_ndt, np.nan)
    for k in range(max_ndt):
        lc = bound_matrix[:, k] != 0
        if lc.sum() > 5:
            congruence[k] = np.mean(np.sign(bound_matrix[lc, k]) == choices_pm[lc])

    ndts = np.full(n_trials, np.nan)
    if ndt is not None:
        ndts[:] = np.clip(rts - 2, 0, int(ndt))
    else:
        if np.any(np.isfinite(congruence)):
            max_cong = np.nanmax(congruence)
            ci = int(np.where(congruence == max_cong)[0][-1])
            ndts[:] = np.clip(rts - 2, 0, ci)

    # ── RT cutoff ────────────────────────────────────────────────────────────
    rt_cutoffs = np.ones(n_trials, dtype=float)
    if rt_cutoff_threshold is not None:
        rt_cutoffs[:] = _compute_rt_cutoff(
            bound_matrix, choices_pm, rts, threshold=rt_cutoff_threshold
        )

    # ── Extract bounds with peak-step correction ──────────────────────────────
    bounds = np.full(n_trials, np.nan)
    for bi in np.where(np.isfinite(ndts))[0]:
        k   = int(ndts[bi])
        mid = bound_matrix[bi, k]

        if peak_step_bound and mid != 0:
            RT        = int(rts[bi])
            t_later   = RT - 1 - k
            t_earlier = RT - 2 - k
            if 0 <= t_earlier < DV.shape[1] and t_later < DV.shape[1]:
                step_in = DV[bi, t_later] - DV[bi, t_earlier]
                if step_in * np.sign(mid) < 0:
                    bounds[bi] = DV[bi, t_earlier]
                    continue
        bounds[bi] = mid

    # ── DTs ──────────────────────────────────────────────────────────────────
    dts = np.maximum(0, rts - ndts - 1)

    return bounds, dts, rts, congruence, rt_cutoffs


def get_good_trial_array(data_table, min_dt=2, min_trial_number=10,
                         block_index=None, apply_rt_cutoff=True):
    """
    Standard trial selection filter.
    Translated from getPigeon_goodTrialArray.m

    Parameters
    ----------
    data_table : pd.DataFrame
        Output of get_data_table (or get_simulated_data_table).
    min_dt : int or None
        Minimum DT (decision time, steps). Excludes trials too short to
        estimate a reliable bound. Default 2.
    min_trial_number : int or None
        Minimum trial number within a block. Excludes early warm-up trials
        where participants are still learning the task. Default 10.
    block_index : int, list, or None
        If given, keep only trials from the specified block(s).
    apply_rt_cutoff : bool
        If True and 'rt_below_cutoff' column is present, excludes trials
        below the per-(block, SNR) RT reliability cutoff computed in
        get_bounds. Default True.

    Returns
    -------
    pd.Series of bool, same index as data_table.
        True for trials that pass all filters (i.e. should be included
        in bound and performance analyses).
    """
    lg = pd.Series(True, index=data_table.index)

    if min_dt is not None:
        lg = lg & (data_table["DT"] >= min_dt)
    if min_trial_number is not None:
        lg = lg & (data_table["trial_number"] >= min_trial_number)
    if block_index is not None:
        lg = lg & data_table["block_index"].isin(
            [block_index] if np.isscalar(block_index) else block_index
        )
    # Exclude wall-hit trials: pigeon reached screen edge, inflating RT/DT
    if "wall_hit" in data_table.columns:
        lg = lg & ~data_table["wall_hit"]
    # Exclude trials below the per-(subject, block, SNR) RT reliability cutoff
    if apply_rt_cutoff and "rt_below_cutoff" in data_table.columns:
        lg = lg & ~data_table["rt_below_cutoff"]

    return lg


def apply_bias_corrections(data_table, bias_file):
    """
    Apply bound bias corrections loaded from a .mat file.
    Translated from getPigeon_biasCorrections.m
    """
    mat = scipy.io.loadmat(bias_file)
    # bias_correction shape: (n_dt_bins, 2, n_snr_bins)
    # dim 1: [intercept, slope] — the linear mapping true = a + b * |measured|
    # Generated by notebooks/Make_biasCorrection.ipynb (Python) or
    # makePigeon_biasCorrections.m (MATLAB).
    bias_correction = mat["boundBiasCorrection"]

    snrs = np.abs(data_table["snr"].to_numpy())
    # Three SNR bins chosen to split the SNR distribution into low/mid/high.
    # Boundaries match the MATLAB implementation (getPigeon_biasCorrections.m).
    # The three bins correspond to generative_means [0.05, 0.10, 0.15] / std 0.15
    # = SNR [0.33, 0.67, 1.0].
    snr_masks = np.column_stack([
        snrs < 0.4,
        (snrs >= 0.4) & (snrs < 0.8),
        snrs >= 0.8,
    ])

    n_dts = bias_correction.shape[0]
    bounds = data_table["bound"].to_numpy(dtype=float).copy()

    # Apply correction per (DT bin, SNR bin).
    # The last DT bin is open-ended (DT >= n_dts) to handle very long trials.
    # Correction formula: corrected = sign(bound) * max(0.005, a + b * |bound|)
    # where [a, b] = bias_correction[dd, :, mm] and 0.005 is a floor to prevent
    # degenerate near-zero bounds.
    for dd in range(n_dts):
        if dd < n_dts - 1:
            ld = data_table["DT"] == (dd + 1)
        else:
            ld = data_table["DT"] >= (dd + 1)

        for mm in range(3):
            ls = ld & snr_masks[:, mm]
            if ls.any():
                new_bounds = np.maximum(
                    0.005,
                    bias_correction[dd, 0, mm] + bias_correction[dd, 1, mm] * np.abs(bounds[ls])
                )
                bounds[ls] = np.sign(bounds[ls]) * new_bounds

    data_table = data_table.copy()
    data_table["bound"] = bounds
    data_table["abs_bound"] = np.abs(bounds)
    return data_table
